name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout orbiton
        uses: actions/checkout@v4
        with:
          path: orbiton
          fetch-depth: 1

      - name: Checkout orbit
        uses: actions/checkout@v4
        with:
          repository: orbitrs/orbit
          path: orbit
          fetch-depth: 1
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout orbit-analyzer
        uses: actions/checkout@v4
        with:
          repository: orbitrs/orbit-analyzer
          path: orbit-analyzer
          fetch-depth: 1
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup workspace for dependencies
        run: |
          echo "Current directory structure:"
          pwd
          ls -la
          
          # Create a workspace Cargo.toml at the root of the checkout directory
          cat > Cargo.toml << 'EOF'
          [workspace]
          members = [
              "orbit",
              "orbit-analyzer",
              "orbiton",
          ]

          [workspace.package]
          version = "0.1.0"
          edition = "2021"
          authors = ["Orbit Team <orbit@example.com>"]
          license = "MIT OR Apache-2.0"
          repository = "https://github.com/orbitrs/orbit"

          [workspace.dependencies]
          serde = { version = "1.0", features = ["derive"] }
          serde_json = "1.0"
          thiserror = "1.0"
          log = "0.4"
          EOF

          # Update orbiton's Cargo.toml to use local paths
          cd orbiton
          sed -i 's|orbit = { git = "https://github.com/orbitrs/orbit.git" }|orbit = { path = "../orbit" }|' Cargo.toml || echo "Failed to update orbit dependency"
          sed -i 's|orbit-analyzer = { git = "https://github.com/orbitrs/orbit-analyzer.git" }|orbit-analyzer = { path = "../orbit-analyzer" }|' Cargo.toml || echo "Failed to update orbit-analyzer dependency"
          
          # Show workspace structure
          echo "Workspace Cargo.toml files:"
          find . -name "Cargo.toml" | sort
          
          # Show dependencies in orbiton's Cargo.toml
          echo "Orbiton dependencies:"
          grep -A 10 "dependencies" orbiton/Cargo.toml

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            . -> target

      - name: Format check
        run: |
          cd orbiton
          cargo fmt --check

      - name: Clippy
        run: |
          cd orbiton
          cargo clippy --all-features --all-targets -- -D warnings

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout orbiton
        uses: actions/checkout@v4
        with:
          path: orbiton
          fetch-depth: 1

      - name: Checkout orbit
        uses: actions/checkout@v4
        with:
          repository: orbitrs/orbit
          path: orbit
          fetch-depth: 1
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout orbit-analyzer
        uses: actions/checkout@v4
        with:
          repository: orbitrs/orbit-analyzer
          path: orbit-analyzer
          fetch-depth: 1
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup workspace for dependencies
        run: |
          echo "Current directory structure:"
          pwd
          ls -la
          
          # Create a workspace Cargo.toml at the root of the checkout directory
          cat > Cargo.toml << 'EOF'
          [workspace]
          members = [
              "orbit",
              "orbit-analyzer",
              "orbiton",
          ]

          [workspace.package]
          version = "0.1.0"
          edition = "2021"
          authors = ["Orbit Team <orbit@example.com>"]
          license = "MIT OR Apache-2.0"
          repository = "https://github.com/orbitrs/orbit"

          [workspace.dependencies]
          serde = { version = "1.0", features = ["derive"] }
          serde_json = "1.0"
          thiserror = "1.0"
          log = "0.4"
          EOF

          # Update orbiton's Cargo.toml to use local paths
          cd orbiton
          sed -i 's|orbit = { git = "https://github.com/orbitrs/orbit.git" }|orbit = { path = "../orbit" }|' Cargo.toml || echo "Failed to update orbit dependency"
          sed -i 's|orbit-analyzer = { git = "https://github.com/orbitrs/orbit-analyzer.git" }|orbit-analyzer = { path = "../orbit-analyzer" }|' Cargo.toml || echo "Failed to update orbit-analyzer dependency"
          
          # Show workspace structure
          echo "Workspace Cargo.toml files:"
          find . -name "Cargo.toml" | sort
          
          # Show dependencies in orbiton's Cargo.toml
          echo "Orbiton dependencies:"
          grep -A 10 "dependencies" orbiton/Cargo.toml

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            . -> target

      - name: Run tests
        run: |
          cd orbiton
          cargo test --all-features
