name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check workspace structure
        run: |
          pwd
          ls -la
          find . -name "Cargo.toml" | sort

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Format check
        run: |
          cd $(find . -name "Cargo.toml" -not -path "*/target/*" | head -1 | xargs dirname)
          cargo fmt --check

      - name: Clippy
        run: |
          cd $(find . -name "Cargo.toml" -not -path "*/target/*" | head -1 | xargs dirname)
          cargo clippy --all-features --all-targets -- -D warnings

  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Check workspace structure
        run: |
          pwd
          ls -la
          find . -name "Cargo.toml" | sort

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Run tests
        run: |
          cd $(find . -name "Cargo.toml" -not -path "*/target/*" | head -1 | xargs dirname)
          cargo test --all-features
