name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  actions: read
  pull-requests: read
  id-token: write

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Format & Lint
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      # Create workspace directory for handling dependencies
      - name: Create workspace directory
        run: |
          mkdir -p $GITHUB_WORKSPACE/orbitrs-workspace
      
      # Checkout repositories
      - name: Checkout orbiton
        uses: actions/checkout@v4
        with:
          path: orbitrs-workspace/orbiton
      
      - name: Checkout orbitui
        uses: actions/checkout@v4
        with:
          repository: orbitrs/orbitui
          path: orbitrs-workspace/orbitui
      
      - name: Checkout orlint
        uses: actions/checkout@v4
        with:
          repository: orbitrs/orlint
          path: orbitrs-workspace/orlint
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libfontconfig1-dev libfreetype6-dev
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy,rustfmt
      
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: orbitrs-workspace/orbiton -> target
      
      - name: Verify dependency paths
        run: |
          cd $GITHUB_WORKSPACE/orbitrs-workspace/orbiton
          if [ ! -f "Cargo.toml" ]; then
            echo "::error::Cargo.toml not found in orbiton directory"
            exit 1
          fi
      
      # Fix workspace configuration for cargo fmt and clippy
      - name: Setup workspace configuration
        working-directory: orbitrs-workspace/orbiton
        run: |
          # Setup proper workspace configuration
          mkdir -p .cargo
          echo '[patch."https://github.com/orbitrs/orbitui.git"]' > .cargo/config.toml
          echo 'orbitui = { path = "../orbitui" }' >> .cargo/config.toml
          echo '[patch."https://github.com/orbitrs/orlint.git"]' >> .cargo/config.toml
          echo 'orlint = { path = "../orlint" }' >> .cargo/config.toml
          
          # Create a temporary workspace configuration
          cp Cargo.toml Cargo.toml.bak
          echo -e "[workspace]\nmembers = [\".\"]\n$(cat Cargo.toml)" > Cargo.toml
      
      - name: Check code formatting
        working-directory: orbitrs-workspace/orbiton
        run: cargo fmt --all -- --check
      
      - name: Run clippy
        working-directory: orbitrs-workspace/orbiton
        run: cargo clippy --features ci --all-targets -- -D warnings
        
      # Restore original Cargo.toml
      - name: Restore Cargo.toml
        working-directory: orbitrs-workspace/orbiton
        run: |
          if [ -f "Cargo.toml.bak" ]; then
            mv Cargo.toml.bak Cargo.toml
          fi
  
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    needs: check
    timeout-minutes: 45
    strategy:
      matrix:
        include:
          # Linux builds
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          # macOS builds  
          - os: macos-latest
            target: x86_64-apple-darwin
          # Windows builds
          - os: windows-latest
            target: x86_64-pc-windows-msvc
      fail-fast: false
    
    steps:
      - name: Create workspace directory
        run: mkdir -p ${{ github.workspace }}/orbitrs-workspace
      
      # Checkout repositories
      - name: Checkout orbiton
        uses: actions/checkout@v4
        with:
          path: orbitrs-workspace/orbiton
      
      - name: Checkout orbitui
        uses: actions/checkout@v4
        with:
          repository: orbitrs/orbitui
          path: orbitrs-workspace/orbitui
          
      - name: Checkout orlint
        uses: actions/checkout@v4
        with:
          repository: orbitrs/orlint
          path: orbitrs-workspace/orlint
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: orbitrs-workspace/orbiton -> target
          key: ${{ matrix.target }}
      
      - name: Install system dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libfontconfig1-dev libfreetype6-dev
      
      - name: Run tests
        working-directory: orbitrs-workspace/orbiton
        run: cargo test --target ${{ matrix.target }} --features ci
  
  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    needs: check
    timeout-minutes: 15
    steps:
      - name: Create workspace directory
        run: mkdir -p ${{ github.workspace }}/orbitrs-workspace
      
      - name: Checkout orbiton
        uses: actions/checkout@v4
        with:
          path: orbitrs-workspace/orbiton
      
      - name: Install cargo-audit
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-audit
      
      - name: Run security audit
        working-directory: orbitrs-workspace/orbiton
        run: cargo audit
  
  outdated-dependencies:
    name: Check Outdated Dependencies
    runs-on: ubuntu-latest
    needs: check
    timeout-minutes: 15
    steps:
      - name: Create workspace directory
        run: mkdir -p ${{ github.workspace }}/orbitrs-workspace
      
      - name: Checkout orbiton
        uses: actions/checkout@v4
        with:
          path: orbitrs-workspace/orbiton
      
      - name: Checkout orbitui
        uses: actions/checkout@v4
        with:
          repository: orbitrs/orbitui
          path: orbitrs-workspace/orbitui
          
      - name: Checkout orlint
        uses: actions/checkout@v4
        with:
          repository: orbitrs/orlint
          path: orbitrs-workspace/orlint
      
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Install cargo-outdated
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-outdated
      
      - name: Check for outdated dependencies
        working-directory: orbitrs-workspace/orbiton
        run: cargo outdated --exit-code 0