name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  release:
    uses: orbitrs/orbit-workflows/.github/workflows/reusable/rust-release.yml@main
    with:
      publish-crate: true
      build-docs: true
      cross-platform-artifacts: true
    secrets:
      CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
