name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    uses: orbitrs/orbit-workflows/.github/workflows/reusable/rust-release.yml@main
    permissions:
      contents: write
    with:
      publish-crate: true
    secrets:
      CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
